# Este script é executado quando a imagem é gerada

FROM php:5.6-fpm

# Os headers para libpng são necessários para compilar o gd
RUN apt-get update -y && apt-get install -y libpng-dev

# Compila e instala as extensões necessárias
RUN docker-php-ext-install mysql mysqli pdo_mysql gd mbstring zip

# RUN docker-php-ext-enable gd


