# Este script é executado quando a imagem é gerada

FROM php:7.0-fpm

# Os headers para compilação da biblioteca gd
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev;

RUN docker-php-ext-install -j$(nproc) iconv;
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/;
RUN docker-php-ext-install -j$(nproc) gd;
RUN docker-php-ext-install -j$(nproc) mcrypt;
RUN mysqli -j$(nproc) pdo_mysql;
RUN docker-php-ext-install -j$(nproc) curl;
RUN docker-php-ext-install -j$(nproc) xml; 
RUN docker-php-ext-install -j$(nproc) mbstring;
RUN docker-php-ext-install -j$(nproc) zip;

# RUN docker-php-ext-enable gd


